### ISSUE TITLE
ADD  EDIT_SLEEP_TIME_OUT

### ISSUE THREAD

**Issue by gupta-vipin** [prdpjngd/fileherobot#1]
Bot stuck while displaying download progress, due to continuous message edit. Try to add a time gap in editing messages. For help you can see PublicLeech by @SpEcHiDe : https://github.com/SpEcHiDe/PublicLeech

**Comment by prdpjngd** [comment]
thx but you can also contribute for this project 

fork and solve this problem I will merge
